config/routes.rb
Rails.application.routes.draw do
  resources :candidate_details
  get 'home/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  namespace :api do
    namespace :v2 do
      resources :mobiles 
      post 'auth/register' , to: 'users#register'
      post 'auth/login' , to: 'users#login'
      get 'test' , to: 'users#test'
       #get 'mobiles/mobiles_login'
       #get 'mobiles/index'
       #post 'mobiles/create'
       post 'mobiles/login'
       post 'mobiles/create'
       get 'mobiles/logout'
       post 'mobiles/user_new'
       post 'mobiles/user_new' => 'mobiles#user_new'
    
    end
  end

  namespace :api do
    namespace :v2 do
      resources :candidateapi 
       post 'candidateapi/create'
       

    
    end
  end

  resources :users
  root 'home#index'
  get 'users/new'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/candidate_detail.rb
class CandidateDetail < ApplicationRecord
  has_one_attached :file
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /@peerlogicsys.com/
end

app/controllers/candidate_details_controller.rb
class CandidateDetailsController < ApplicationController
  before_action :set_candidate_detail, only: [:show, :edit, :update, :destroy]

  # GET /candidate_details
  # GET /candidate_details.json
  def index
    @candidate_details = CandidateDetail.all
  end

  # GET /candidate_details/1
  # GET /candidate_details/1.json
  def show
  end

  # GET /candidate_details/new
  def new
    @candidate_detail = CandidateDetail.new
  end

  # GET /candidate_details/1/edit
  def edit
  end

  # POST /candidate_details
  # POST /candidate_details.json
  def create
    @candidate_detail = CandidateDetail.new(candidate_detail_params)

    respond_to do |format|
      if @candidate_detail.save
        format.html { redirect_to @candidate_detail, notice: 'Candidate detail was successfully created.' }
        format.json { render :show, status: :created, location: @candidate_detail }
      else
        format.html { render :new }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidate_details/1
  # PATCH/PUT /candidate_details/1.json
  def update
    respond_to do |format|
      if @candidate_detail.update(candidate_detail_params)
        format.html { redirect_to @candidate_detail, notice: 'Candidate detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate_detail }
      else
        format.html { render :edit }
        format.json { render json: @candidate_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate_details/1
  # DELETE /candidate_details/1.json
  def destroy
    @candidate_detail.destroy
    respond_to do |format|
      format.html { redirect_to candidate_details_url, notice: 'Candidate detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate_detail
      @candidate_detail = CandidateDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def candidate_detail_params
      params.require(:candidate_detail).permit(:first, :last, :email, :phone, :degree, :percentage, :experience, :platform, :file)
    end
end

app/helpers/candidate_details_helper.rb
module CandidateDetailsHelper
end

app/views/candidate_details/_form.html.erb
<%= form_with(model: candidate_detail, local: true) do |form| %>
  <% if candidate_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate_detail.errors.count, "error") %> prohibited this candidate_detail from being saved:</h2>

      <ul>
        <% candidate_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first %>
    <%= form.text_field :first %>
  </div>

  <div class="field">
    <%= form.label :last %>
    <%= form.text_field :last %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :degree %>
    <%= form.text_field :degree %>
  </div>

  <div class="field">
    <%= form.label :percentage %>
    <%= form.text_field :percentage %>
  </div>

  <div class="field">
    <%= form.label :experience %>
    <%= form.text_field :experience %>
  </div>

  <div class="field">
    <%= form.label :platform %>
    <%= form.text_field :platform %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/candidate_details/edit.html.erb
<h1>Editing Candidate Detail</h1>

<%= render 'form', candidate_detail: @candidate_detail %>

<%= link_to 'Show', @candidate_detail %> |
<%= link_to 'Back', candidate_details_path %>

app/views/candidate_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidate Details</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Degree</th>
      <th>Percentage</th>
      <th>Experience</th>
      <th>Platform</th>
      <th>Cv</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidate_details.each do |candidate_detail| %>
      <tr>
        <td><%= candidate_detail.first %></td>
        <td><%= candidate_detail.last %></td>
        <td><%= candidate_detail.email %></td>
        <td><%= candidate_detail.phone %></td>
        <td><%= candidate_detail.degree %></td>
        <td><%= candidate_detail.percentage %></td>
        <td><%= candidate_detail.experience %></td>
        <td><%= candidate_detail.platform %></td>
        <td><%= link_to 'Download', candidate_detail.file, download: '' %></td>
        <td><%= link_to 'Show', candidate_detail %></td>
        <td><%= link_to 'Edit', edit_candidate_detail_path(candidate_detail) %></td>
        <td><%= link_to 'Destroy', candidate_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate Detail', new_candidate_detail_path %>

app/views/candidate_details/new.html.erb
<h1>New Candidate Detail</h1>

<%= render 'form', candidate_detail: @candidate_detail %>

<%= link_to 'Back', candidate_details_path %>

app/views/candidate_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @candidate_detail.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @candidate_detail.last %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidate_detail.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @candidate_detail.phone %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @candidate_detail.degree %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @candidate_detail.percentage %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @candidate_detail.experience %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @candidate_detail.platform %>
</p>

<%= link_to 'Download', @candidate_detail.file, download: '' %>

<%= link_to 'Edit', edit_candidate_detail_path(@candidate_detail) %> |
<%= link_to 'Back', candidate_details_path %>